# .streamlit/secrets.toml  (DO NOT COMMIT REAL SECRETS TO GIT)

[connections.snowflake]
account = "qzyzbds-ngb00309"
user = "SATHISHKUMAR"
password = "LakshanaSarja@12"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
